#!/bin/bash

# MySQL database credentials
# username="dbuser1"
# password=''

# Prompt for MySQL password
# echo -n "Enter MySQL password for user $username: "
# stty -echo  # Turn off echoing
# read password
# stty echo  # Turn echoing back on
# echo  # Add a newline after the password input

# Get current date
# current_date=$(date -d "1 day ago" +'%Y%m%d')

# Define the path to the MySQL option file
mariadb_option_file="/etc/mysql/mariadb_client.cnf"

# Get the current date in YYYYMMDD format
current_date=$(date +'%Y%m%d')


# First database
database1="DB1"
backup_dir1="/backups/DB1"  # Change this to the directory of the first backup file

# Second database
database2="DB2"
backup_dir2="/backups/DB2"  # Change this to the directory of the second backup file

# Third database
database3="DB3"
backup_dir3="/backups/DB3"

# Restore the first database
mysql --defaults-file="$mariadb_option_file" "$database1" < "$backup_dir1/${database1}_${current_date}.sql"

# Restore the second database
mysql --defaults-file="$mariadb_option_file" "$database2" < "$backup_dir2/${database2}_${current_date}.sql"

# Restore the third database
mysql --defaults-file="$mariadb_option_file" "$database3" < "$backup_dir3/${database3}_${current_date}.sql"

echo "DBS - DB1, DB2 & DB3 databases restored successfully."